openapi: 3.1.0

info:
  title: Monday Secretary API
  version: "1.0.0"

servers:
  - url: https://health-api-server.onrender.com

paths:

  /functions/get_health_data:
    post:
      operationId: getHealthData
      summary: 体調データを取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HealthRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /functions/get_work_data:
    post:
      operationId: getWorkData
      summary: 業務メモを取得
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetWorkDataRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkDataResponse'

  /functions/calendar_event:
    post:
      operationId: calendarEvent
      summary: カレンダー操作
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalendarRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CalendarResponse'

  /functions/create_memory:
    post:
      operationId: createMemory
      summary: Notion にメモを保存
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoryRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoryResponse'

components:
  schemas:

    # ---------- Health ----------
    HealthRequest:
      type: object
      properties:
        mode:
          type: string
          enum: [latest, compare, period, dailySummary]
          default: latest
        sheet_url:
          type: string
          nullable: true
        start_date:
          type: string
          format: date
          nullable: true
        end_date:
          type: string
          format: date
          nullable: true

    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: array
          items:
            $ref: '#/components/schemas/HealthItem'

    HealthItem:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        sleep_hours:
          type: number
        slept_well:
          type: boolean
        weight:
          type: number
          nullable: true
        energy:
          type: string
          nullable: true
        mood:
          type: string
          nullable: true
        memo:
          type: string
          nullable: true

    # ---------- Work ----------
    GetWorkDataRequest:
      type: object
      required: [mode]
      properties:
        mode:
          type: string
          enum: [latest, period]
        start_date:
          type: string
          format: date
          nullable: true
        end_date:
          type: string
          format: date
          nullable: true

    WorkDataResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        data:
          type: array
          items:
            $ref: '#/components/schemas/WorkItem'

    WorkItem:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        box_setup_9am:
          type: boolean
        tasks_after_10am:
          type: string
        rest_minutes_am:
          type: number
        fatigue_level_am:
          type: string
        comment_am:
          type: string
          nullable: true
        box_collected_3pm:
          type: boolean
        tasks_pm:
          type: string
        rest_minutes_pm:
          type: number
        fatigue_level_pm:
          type: string
        comment_pm:
          type: string
          nullable: true
        daily_summary:
          type: string
          nullable: true

    # ---------- Calendar ----------
    CalendarRequest:
      type: object
      required: [action]
      properties:
        action:
          type: string
          enum: [insert, get, update, delete]
        calendar_id:
          type: string
          nullable: true
        summary:
          type: string
          nullable: true
        start:
          type: string
          format: date-time
          nullable: true
        end:
          type: string
          format: date-time
          nullable: true
        event_id:
          type: string
          nullable: true

    CalendarResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        event:
          $ref: '#/components/schemas/CalendarEvent'

    CalendarEvent:
      type: object
      properties:
        id:
          type: string
        summary:
          type: string
        calendar_id:
          type: string
        start:
          type: string
          format: date-time
        end:
          type: string
          format: date-time

    # ---------- Memory ----------
    MemoryRequest:
      type: object
      required: [title, summary, category, emotion, reason]
      properties:
        title:
          type: string
        summary:
          type: string
        detail:
          type: string
          nullable: true
        category:
          type: string
          enum:
            - スケジュール
            - 創作
            - 体調
            - 仕事
            - 遊び
            - 思い出
            - 感情
            - 思考
            - その他
        emotion:
          type: string
          enum: [嬉しい, 悲しい, 怒り, 楽しい, 悔しい, 辛い]
        reason:
          type: string
        timestamp:
          type: string
          format: date-time
          nullable: true

    MemoryResponse:
      type: object
      properties:
        status:
          type: string
          example: success
        saved_memory:
          $ref: '#/components/schemas/SavedMemory'

    SavedMemory:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        summary:
          type: string
        category:
          type: string
        emotion:
          type: string
        reason:
          type: string
        timestamp:
          type: string
          format: date-time
