openapi: 3.1.0
info:
  title: Monday Secretary API
  version: 1.0.0
servers:
  - url: https://health-api-server.onrender.com

paths:
  # ─── Health ─────────────────────────────
  /functions/get_health_data:
    post:
      operationId: getHealthData
      summary: 体調データを取得
      tags: [Health]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HealthRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  # ─── Work ───────────────────────────────
  /functions/get_work_data:
    post:
      operationId: getWorkData
      summary: 業務メモを取得
      tags: [Work]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetWorkDataRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkDataResponse"

  # ─── Acceptance ─────────────────────────
  /functions/get_acceptance_data:
    post:
      operationId: getAcceptanceData
      summary: 自己受容メモを取得
      tags: [Acceptance]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AcceptanceRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AcceptanceResponse"

  # ─── Calendar ───────────────────────────
  /functions/calendar_event:
    post:
      operationId: calendarEvent
      summary: カレンダー操作
      tags: [Calendar]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CalendarRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CalendarResponse"

components:
  schemas:
    # ---------- Health ----------
    HealthRequest:
      type: object
      required: [mode]
      properties:
        mode:
          type: string
          enum: [latest, compare, period, dailySummary]
          default: latest
        sheet_url: { type: string, nullable: true }
        start_date: { type: string, format: date, nullable: true }
        end_date:   { type: string, format: date, nullable: true }

    HealthItem:
      type: object
      properties:
        timestamp:   { type: string, format: date-time }
        sleep_hours: { type: number }
        slept_well:  { type: boolean }
        weight:      { type: number, nullable: true }
        energy:      { type: string, nullable: true }
        mood:        { type: string, nullable: true }
        memo:        { type: string, nullable: true }

    HealthResponse:
      type: object
      properties:
        status: { type: string, example: "success" }
        data:
          type: array
          items:
            $ref: "#/components/schemas/HealthItem"

    # ---------- Work ----------
    GetWorkDataRequest:
      type: object
      required: [mode]
      properties:
        mode:
          type: string
          enum: [latest, period]
        start_date: { type: string, format: date, nullable: true }
        end_date:   { type: string, format: date, nullable: true }

    WorkItem:
      type: object
      properties:
        timestamp:           { type: string, format: date-time }
        box_setup_9am:       { type: boolean }
        tasks_after_10am:    { type: string }
        rest_minutes_am:     { type: number }
        fatigue_level_am:    { type: string }
        comment_am:          { type: string, nullable: true }
        box_collected_3pm:   { type: boolean }
        tasks_pm:            { type: string }
        rest_minutes_pm:     { type: number }
        fatigue_level_pm:    { type: string }
        comment_pm:          { type: string, nullable: true }
        daily_summary:       { type: string, nullable: true }

    WorkDataResponse:
      type: object
      properties:
        status: { type: string, example: "success" }
        data:
          type: array
          items:
            $ref: "#/components/schemas/WorkItem"

    # ---------- Acceptance ----------
    AcceptanceRequest:
      type: object
      required: [mode]
      properties:
        mode:
          type: string
          enum: [latest, period]
          default: latest
        start_date: { type: string, format: date, nullable: true }
        end_date:   { type: string, format: date, nullable: true }

    AcceptanceItem:
      type: object
      properties:
        timestamp:
          type: string
          format: date
          description: タイムスタンプ
        currentFeeling:
          type: string
          description: 今の気持ち
        mostImpressiveEmotion:
          type: string
          description: 一番印象的だった感情
        thoughtFragments:
          type: string
          nullable: true
          description: 今日浮かんだ思考の断片
        wordsToMyself:
          type: string
          nullable: true
          description: 今日の自分にかけたい言葉
        acceptedMoment:
          type: string
          nullable: true
          description: 今日、自分を受け入れられた瞬間はある
        notes:
          type: string
          nullable: true
          description: 書き残しておきたいこと

    AcceptanceResponse:
      type: object
      properties:
        status: { type: string, example: "success" }
        data:
          type: array
          items:
            $ref: "#/components/schemas/AcceptanceItem"

    # ---------- Calendar ----------
    CalendarRequest:
      type: object
      required: [action]
      properties:
        action:
          type: string
          enum: [insert, get, update, delete]
        calendar_id: { type: string, nullable: true }
        summary:     { type: string, nullable: true }
        start:       { type: string, format: date-time, nullable: true }
        end:         { type: string, format: date-time, nullable: true }
        event_id:    { type: string, nullable: true }

    CalendarEvent:
      type: object
      properties:
        id:          { type: string }
        summary:     { type: string }
        calendar_id: { type: string }
        start:       { type: string, format: date-time }
        end:         { type: string, format: date-time }

    CalendarResponse:
      type: object
      properties:
        status: { type: string, example: "success" }
        event:
          $ref: "#/components/schemas/CalendarEvent"
